<?php

namespace App\Filament\Pages\Auth;

use Filament\Forms\Form;
use Filament\Pages\Auth\Login as BaseLogin;

class Login extends BaseLogin
{
    public function registerAction(): \Filament\Actions\Action
    {
        return parent::registerAction()->label('Ainda não tem uma conta? Crie uma aqui!'); // TODO: Change the autogenerated stub
    }

    public function getTitle(): string
    {
        return 'Entrar';
    }

    public function getHeading(): string
    {
        return 'Entrar';
    }

    public function getFormActions(): array
    {
        return [
          $this->getAuthenticateFormAction()->label('Entrar'),
        ];
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            $this->getEmailFormComponent()
            ->label('Email'),
            $this->getPasswordFormComponent()
            ->label('Senha'),
            $this->getRememberFormComponent()
            ->label('Lembre-me'),
        ]);
    }
}
